version: '3'
services:
  backend:
    network_mode: "host"
    build:
      network: host
      context: /home/public
      dockerfile: /home/public/project-collabsphere/backend/Dockerfile
    # ports:
    #   - "4000:4000/tcp"
    #   - "3030:3030/tcp"
    #   - "3030:3030/udp"
    #   - "40000-49999:40000-49999/udp"
    env_file:
      - /home/public/project-collabsphere/backend/.env

  frontend:
    build:
      context: /home/public
      dockerfile: /home/public/project-collabsphere/frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - /home/public/project-collabsphere/frontend/.env
